### PR TITLE
feat: add `values_available` function

### PR DESCRIPTION
**Pull request by c-cube**
close #4, with a much simpler implementation which I believe also works?

ping @pdonadeo to discuss

### CODE REVIEW

**Comment by pdonadeo** [comment]
@c-cube your implementation is indeed much simpler but the semantics of `values_available` is quite different: `values_available` should block. It's like a `read`, but the call doesn't remove the value.

It's intended to be used in combination with `read` and `Lwt.pick` to create a "read with timeout" like the fragment of code in #4 

If you simply `pick` a read and a timeout function one of the following events can happen:
1. `read` becomes determined before the timeout: in this case you read the value and it's OK.
2. `timeout` becomes determined before the read: in this case `pick` is determined with a Timeout value but the other thread continues silently and you eventually lose the value.

Maybe the name `values_available` is not a good choice.

The real use case is this one: in several industrial application I have cooperative threads listening for events, pushed in a queue by other threads, for example: a packet of [MODBUS](https://en.wikipedia.org/wiki/Modbus) data is read from a serial line (RS485), checked and then sent as a high level message (an OCaml value) to another thread.

This thread is a simple never ending loop waiting for a message. In the loop body the message is processed but there is also an exit condition, for example if the program receives a signal. The `read` at the beginning of the loop must have a timeout, otherwise it will block forever if no data arrives from the serial line. Pseudocode:
```python
let rec loop () =
    while read_with_timeout(x):
        is x timeout:
            if should_i_exit:
                exit
            else:
                loop ()
        is x a value:
            process_that_value
            loop()
```

**Comment by pdonadeo** [comment]
I hope it's clear: reading my comment again leave me a sense of confusion... :sweat_smile:

**Comment by c-cube** [comment]
basically you want it to return `(Yes | No | PipeClosed) Lwt.t`, right? But if you wait, `No` should not be an option (since until the pipe is closed one never knows whether more data might arrive).

I think it's a valuable feature but that's got to be a simpler way of doing it (possibly by imitating `read` but without consuming the value).

**Comment by pdonadeo** [comment]
Yep, precisely. I agree with you that my implementation is a bit convoluted. I'm going to rethink the problem next weekend, let's see if I can find a clean solution.

**Pull request closed without merging**
