### PR TITLE
Fix for of_array and of_string

### PR DESCRIPTION
**Pull request by FardaleM**

### CODE REVIEW

**Comment by c-cube** [comment]
looks like this could use a test, I'm not sure I see what the bug was

**Comment by FardaleM** [comment]
I found it by writing test. But I was planing to add all tests in a later PR.
For the of_array, it is not a bug, it is just redundancy.
For the of_string, `Lwt_main.run Lwt_pipe.(to_string (of_string s))` does not terminate without this change. For me it look like a bug because it is not consistent with of_array and of_list and I don't know why we want to let the pipe open at the end of the string.

**Comment by c-cube** [comment]
can you add the tests in this same PR? :)

**Comment by c-cube** [comment]
:100: thanks a lot!

**Pull request merged**
